global:
  apiLayerApiKey: ""
  ip2WhoisApiKey: ""
  whoisXmlApiKey: ""
  apiLayerWhoisUrl: "https://api.apilayer.com/whois/query"
  ip2WhoisUrl: "https://api.ip2whois.com/v2"
  notifyMethod: "qiwei"
  afterMonths: 12
dingding:
    alertNotifyUrl: "https://oapi.dingtalk.com/robot/send?access_token="
    msgType: "markdown"
    alertTitle: "域名续费"
    alertTemplate: "[whois]标题: **域名即将到期** \n\n
      域名: **%s** \n\n
      过期时间: %s"
    unknownTitle: "域名续费-查询异常"
    unknownTemplate: "[whois]标题: **域名信息查询异常** \n\n
      域名: **%s**"
    atWho:
      - ""  # 如果要at其他人，也需要在template里显示注明 @xxx
    isAtAll: "false"
qiwei:
  alertNotifyUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key="
  msgType: "markdown"
  alertTitle: "域名即将到期，请相关同事注意。"
  alertTemplate: "
    >域名:<font color=\"comment\">%s</font>\n
    >过期时间:<font color=\"comment\">%s</font>\n"
  unknownTitle: "域名存续信息查询异常"
  unknownTemplate: "
    >域名:<font color=\"comment\">%s</font>\n"
domain:
  - "dingtalk.com"
manifest:
  domainExpireList:
    qq.com: "2031-07-27"

